// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    Avatar: typeof import('./src/components/Avatar/Avatar.vue')['default']
    Card: typeof import('./src/components/Card/Card.vue')['default']
    ElOption: typeof import('element-plus/es')['ElOption']
    ElScrollbar: typeof import('element-plus/es')['ElScrollbar']
    ElSelect: typeof import('element-plus/es')['ElSelect']
    Header: typeof import('./src/components/Header/Header.vue')['default']
    Loader: typeof import('./src/components/Loader/Loader.vue')['default']
    Profile: typeof import('./src/components/Profile/Profile.vue')['default']
    ProjectsList: typeof import('./src/components/ProjectsList/ProjectsList.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SearchForm: typeof import('./src/components/SearchForm/SearchForm.vue')['default']
  }
}
